name: Bug Report
description: "If something is not working the way it should, report it here."
title: "[Bug]: "
labels: [ "bug" ]
assignees:
  - Einhornyordle
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: "Which version of the mod did you use when you encountered the bug?"
      placeholder: "v0.1.4"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: reality
    attributes:
      label: Actual behavior
      description: "A clear and concise description of what actually happened instead."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context about the problem here."
