blank_issues_enabled: false
contact_links:
  - name: Discussions, Questions, Showcase and more
    url: https://github.com/Einhornyordle/RepoLeveling/discussions
    about: For pretty much everything else that is not a bug report or a feature requests, please use the discussions tab instead.
