name: Feature request
description: "Submit improvement suggestions here."
title: "[Suggestion]: "
labels: [ "enhancement" ]
assignees:
  - Einhornyordle
body:
  - type: textarea
    id: description
    attributes:
      label: Describe your idea
      description: "What would you like to see added to/changed in the mod?"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: "A clear and concise description of any alternative solutions or features you've considered."
  - type: textarea
    id: reality
    attributes:
      label: Additional context
      description: "Add any other context about the problem here."
